# Generated by Django 5.2.5 on 2025-09-04 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(editable=False, max_length=255)),
                ('employer_location', models.CharField(blank=True, max_length=255)),
                ('number_employees', models.PositiveIntegerField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=255)),
                ('glassdoor_score', models.DecimalField(blank=True, decimal_places=1, help_text='Rating out of 5.0', max_digits=2, null=True)),
                ('diversity_score', models.DecimalField(blank=True, decimal_places=1, help_text='Rating out of 5.0', max_digits=2, null=True)),
                ('openings_number', models.PositiveIntegerField(blank=True, help_text='Number of current job openings', null=True)),
                ('mission_statement', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('occupation', models.CharField(max_length=120)),
                ('good_fit_occupations', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('expertise', models.TextField(blank=True)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='audit.pair')),
            ],
        ),
        migrations.CreateModel(
            name='PairApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(editable=False, max_length=120)),
                ('job_title', models.CharField(max_length=255)),
                ('job_text', models.TextField()),
                ('job_location', models.CharField(blank=True, max_length=255)),
                ('days_open', models.PositiveIntegerField(blank=True, default=0, help_text='Number of days open')),
                ('work_mode', models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('in_person', 'In-person')], default='in_person', max_length=20)),
                ('job_link', models.URLField(blank=True)),
                ('job_board', models.CharField(blank='True', choices=[('', 'Select a job board'), ('indeed', 'Indeed'), ('glassdoor', 'Glassdoor'), ('ziprecruiter', 'ZipRecruiter'), ('other', 'Other')], max_length=50)),
                ('job_board_other', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='audit.employer')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='audit.pair')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('occupation', 'employer'), name='unique_occupation_employer_application')],
            },
        ),
    ]
