# Generated by Django 5.2.5 on 2025-09-02 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255, unique=True)),
                ('normalized_name', models.CharField(editable=False, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('occupation', models.CharField(max_length=120)),
                ('good_fit_occupations', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('expertise', models.TextField(blank=True)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='audit.pair')),
            ],
        ),
        migrations.CreateModel(
            name='PairApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(max_length=120)),
                ('job_title', models.CharField(max_length=255)),
                ('job_text', models.TextField()),
                ('job_location', models.CharField(blank=True, max_length=255)),
                ('work_mode', models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('in_person', 'In-person')], default='in_person', max_length=20)),
                ('job_link', models.URLField(blank=True)),
                ('job_board', models.CharField(choices=[('indeed', 'Indeed'), ('glassdoor', 'Glassdoor'), ('ziprecruiter', 'ZipRecruiter'), ('other', 'Other')], default='other', max_length=50)),
                ('job_board_other', models.CharField(blank=True, help_text="If 'Other' selected, specify the job board name", max_length=255)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='audit.employer')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='audit.pair')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('pair', 'employer', 'job_link'), name='unique_pair_application')],
            },
        ),
    ]
