# Generated by Django 5.2.5 on 2025-09-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairapplication',
            name='job_board_other',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pairapplication',
            name='occupation',
            field=models.CharField(editable=False, max_length=120),
        ),
    ]
