# Generated by Django 5.2.5 on 2025-09-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairapplication',
            name='callback_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pairapplication',
            name='callback_medium',
            field=models.CharField(blank=True, choices=[('phone', 'Phone'), ('personalized_email', 'Personalized Email'), ('standardized_email', 'Standardized Email')], max_length=20),
        ),
        migrations.AddField(
            model_name='pairapplication',
            name='callback_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pairapplication',
            name='callback_received',
            field=models.BooleanField(default=False),
        ),
    ]
