# Generated by Django 5.2.5 on 2025-09-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_pairapplication_callback_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairapplication',
            name='callback_medium',
            field=models.CharField(blank=True, choices=[('phone', 'Phone call'), ('personalized_email', 'Personalized email'), ('standardized_email', 'Standardized/automated email'), ('text', 'Text message'), ('other', 'Other')], max_length=20),
        ),
    ]
