# Generated by Django 5.2.5 on 2025-09-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_pairapplication_job_board_other_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairapplication',
            name='occupation',
            field=models.CharField(max_length=120),
        ),
    ]
