# Generated by Django 5.2.5 on 2025-09-04 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_pairapplication_callback_medium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pairapplication',
            name='callback_date',
        ),
        migrations.RemoveField(
            model_name='pairapplication',
            name='callback_medium',
        ),
        migrations.RemoveField(
            model_name='pairapplication',
            name='callback_notes',
        ),
        migrations.RemoveField(
            model_name='pairapplication',
            name='callback_received',
        ),
        migrations.CreateModel(
            name='CallbackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callback_received', models.BooleanField(default=False)),
                ('callback_date', models.DateField(blank=True, null=True)),
                ('callback_medium', models.CharField(blank=True, choices=[('phone', 'Phone call'), ('personalized_email', 'Personalized email'), ('standardized_email', 'Standardized/automated email'), ('text', 'Text message'), ('other', 'Other')], max_length=20)),
                ('callback_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callbacks', to='audit.pairapplication')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callbacks', to='audit.profile')),
            ],
            options={
                'unique_together': {('profile', 'application')},
            },
        ),
    ]
