# Generated by Django 5.2.5 on 2025-09-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_pairapplication_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairapplication',
            name='occupation',
            field=models.CharField(editable=False, max_length=120),
        ),
    ]
