# Generated by Django 5.2.5 on 2025-09-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_remove_pairapplication_callback_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callbacklog',
            name='callback_received',
        ),
        migrations.AddField(
            model_name='callbacklog',
            name='callback_status',
            field=models.CharField(choices=[('no_info', 'No Info'), ('callback', 'Callback Received'), ('rejection', 'Rejection')], default='no_info', max_length=20),
        ),
    ]
