# Generated by Django 5.2.5 on 2025-09-03 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_alter_pairapplication_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairapplication',
            name='occupation',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='audit.pair'),
        ),
        migrations.AlterField(
            model_name='pairapplication',
            name='pair',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='audit.pair'),
        ),
    ]
