# Generated by Django 5.2.5 on 2025-09-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_remove_callbacklog_callback_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pair',
            name='archetype',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pair',
            name='location',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='pair',
            name='sublocation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='resume_idx',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='resume_pdf',
            field=models.FileField(blank=True, null=True, upload_to='resumes/pdfs/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='template_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
