# Generated by Django 5.2.5 on 2025-09-03 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_alter_pairapplication_occupation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairapplication',
            name='pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='audit.pair'),
        ),
    ]
