# Generated by Django 5.2.5 on 2025-09-03 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_alter_pairapplication_pair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairapplication',
            name='occupation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='audit.pair'),
        ),
    ]
