# Generated by Django 5.2 on 2025-09-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_pair_archetype_pair_location_pair_sublocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairapplication',
            name='status',
            field=models.CharField(choices=[('draft', 'Work in Progress'), ('submitted', 'Submitted')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='pairapplication',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
