# Generated by Django 5.2.5 on 2025-09-03 17:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0008_alter_pairapplication_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pairapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
