# Generated by Django 5.2.5 on 2025-09-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0009_pairapplication_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pairapplication',
            name='unique_pair_application',
        ),
        migrations.AddConstraint(
            model_name='pairapplication',
            constraint=models.UniqueConstraint(fields=('occupation', 'employer'), name='unique_occupation_employer_application'),
        ),
    ]
