# Generated by Django 5.2.5 on 2025-09-03 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0010_remove_pairapplication_unique_pair_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='employer_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employer',
            name='industry',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employer',
            name='number_employees',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
